config/routes.rb
Rails.application.routes.draw do
  devise_for :controllers
  devise_for :model1, controllers: { sessions: 'model1s/sessions' }
defaults format: :json do
  resource :bot, only: %i[create]
end
root 'posts#index', as: 'home'
get 'about' => 'pages#about', as: 'about'
get 'new' => 'posts#new', as: 'new'
get 'moderate' => 'moderation#moderate', as: 'moderate'
patch 'confirm' => 'moderation#confirm', as: 'confirm'
delete 'destroy' => 'moderation#destroy', as: 'destroy'
get 'laba1' => 'posts#laba1', as: 'laba1'
get 'category' => 'categories#index', as: 'cat'
get 'newcategory' => 'categories#new', as: 'newcat'
get 'postss' => 'posts#postss', as: 'postss'
get '/posts/search' => 'posts#search', as: 'search_posts'
get '/users/search' => 'users#search', as: 'search_users'
get 'user_posts/:model1_id' => 'posts#user', as: :user_posts
get 'allusers' => 'users#allusers', as: 'allusers'
get 'sendmassage' => 'bots#clientadmin', as: 'sendmassage'
get 'sendmassageadmin' => 'bots#clientuser', as: 'sendmassageadmin'
get 'comments' => 'bots#comments', as: 'comments'
get 'destroyy' => 'bots#destroy', as: 'destroyy'
patch 'resetchaid' => 'bots#resetchatid', as: 'resetchatid'
resources :moderation
resources :categories
resources :users
resources :posts do
    resources :comments
end
end

app/controllers/moderation_controller.rb
class ModerationController < ApplicationController

    def moderate
        if model1_signed_in? && ( current_model1.admin? || current_model1.moderator?)
            @post = Post.where(moderated: false).paginate(page: params[:page], per_page: 2)
            @post=@post.all.order(created_at: :desc)
        else
            redirect_to posts_path, alert: 'Вы не можете перейти по этой ссылке'
        end
    end

    def show
        if model1_signed_in? && ( current_model1.admin? || current_model1.moderator?)
            @post=Post.find(params[:id])
        else
            redirect_to posts_path, alert: 'Вы не можете перейти по этой ссылке'
        end
    end

    def confirm
        @post=Post.find(params[:id])
        @message = "Новый пост создан: #{@post.title}\nКатегория: #{@post.category.name}\n"
        @user=@post.model1.email
        @post.update(moderated: 1, moderated_at: Time.now)
        @user1=@post.model1
        @chat_id=@user1.chatid
        @postitle=@post.title
        @category = @post.category
        subscriber = @category.subscribers.pluck(:chat_id)
        @message2="В категории '#{@category.name}' вышел новый пост!\nНазвание: #{@post.title}\nАвтор: #{@post.model1.email}"
        redirect_to controller: 'bots', action: 'clientadmin', message: @message, post: @post, user: @user, chat_id: @chat_id, postitle: @postitle, subscriber: subscriber, message2: @message2
    end

    def destroy
        @post=Post.find(params[:id])
        @user1=@post.model1
        @chat_id=@user1.chatid
        @post.destroy
        if @chat_id.present?
            @message="Ваш пост '#{@post.title}' был отклонен и удален, так как он нарушает правила нашего сайта"
            redirect_to controller: 'bots', action: 'destroy', user: @user, chat_id: @chat_id, message: @message
        else
            redirect_to moderate_path, alert: "Пост ты успешно отклонен"
        end
    end

end

app/helpers/moderation_helper.rb
module ModerationHelper
end

app/views/moderation/moderate.html.erb
<h1 align="center">Модерация</h1>
<br>
<% @i=1 %>
</h4>
<br><br>
<% @post.each do |post| %>
    <h5><%= link_to "Статья №"+@i.to_s+" "+post.title.to_s, moderation_path(post)%> <% @i=@i+1 %> </h5>
    <% if post.model1 %>
    <h6>Автор: <%= link_to post.model1.email, user_posts_path( post.model1 ) if post.model1%></h6>
    <% end %>
    <h6>Категория: <%= link_to post.category.name, category_path(post.category)%></h6>
    <%= post.body %> 
    <br>
    <h7>Дата написания: <%= post.created_at.strftime('%d-%m-%Y')%></h7>
    <br><br><br>
<% end %>
<br>
<%= will_paginate @post %>

app/views/moderation/show.html.erb
<h2 align="center"><%= @post.title %> </h2>
<h6>Категория: <%= link_to @post.category.name, category_path(@post.category)%></h6>
<% if @post.model1 %>
<h6>Автор: <%= link_to @post.model1.email, user_posts_path( @post.model1 )%></h6>
<% end %>
<% if @post.moderated!=nil %>
<% if @post.moderated==true %>
<h6 style="color: green">Moderated: <%= @post.moderated %></h6>
<% elsif @post.moderated==false %>
<h6 style="color: red">Moderated: <%= @post.moderated %></h6>
<% end %>
<% end %>
<br>
<p> <%= @post.body %> </p>
<hr><br>
<%= link_to 'Одобрить', confirm_path(id: @post.id), method: :patch, data: { confirm: 'Вы уверены?' }, :class=>"btn btn-success" %>
<%= link_to "Отклонить", destroy_path(id: @post.id), method: :delete, data: {confirm: "Вы уверены что хотите отклонить статью? Это приведет к ее удалению"}, :class => 'btn btn-danger' %>