config/routes.rb
Rails.application.routes.draw do
  devise_for :controllers
  devise_for :model1, controllers: { sessions: 'model1s/sessions' }
defaults format: :json do
  resource :bot, only: %i[create]
end
root 'posts#index', as: 'home'
get 'about' => 'pages#about', as: 'about'
get 'new' => 'posts#new', as: 'new'
get 'moderate' => 'moderation#moderate', as: 'moderate'
patch 'confirm' => 'moderation#confirm', as: 'confirm'
delete 'destroy' => 'moderation#destroy', as: 'destroy'
get 'laba1' => 'posts#laba1', as: 'laba1'
get 'category' => 'categories#index', as: 'cat'
get 'newcategory' => 'categories#new', as: 'newcat'
get 'postss' => 'posts#postss', as: 'postss'
get '/posts/search' => 'posts#search', as: 'search_posts'
get '/users/search' => 'users#search', as: 'search_users'
get 'user_posts/:model1_id' => 'posts#user', as: :user_posts
get 'allusers' => 'users#allusers', as: 'allusers'
get 'sendmassage' => 'bots#clientadmin', as: 'sendmassage'
get 'sendmassageadmin' => 'bots#clientuser', as: 'sendmassageadmin'
get 'comments' => 'bots#comments', as: 'comments'
get 'destroyy' => 'bots#destroy', as: 'destroyy'
patch 'resetchaid' => 'bots#resetchatid', as: 'resetchatid'
resources :moderation
resources :categories
resources :users
resources :posts do
    resources :comments
end
end

app/models/post.rb
class Post < ApplicationRecord
    has_many :comments, dependent: :destroy
    belongs_to :category
    belongs_to :model1
    validates :title, presence: true, length: {minimum: 5}   
    validates :category_id, presence: true
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
    before_action :authenticate_user!, except: [:index, :show, :search]

    def index
        @post = Post.where(moderated: true).paginate(page: params[:page], per_page: 2)
        @post=@post.all.order(moderated_at: :desc)
    end 

    
    def search
        @post = Post.where("title LIKE ? AND moderated = ?", "%#{params[:query]}%", 1)
    end

    def new
        @post = current_model1.posts.build
        @categories=Category.all.order(:name)
    end

    def show
        @post=Post.find(params[:id])
    end
    
    def edit
        @post=Post.find(params[:id])
        if model1_signed_in? && current_model1 == @post.model1
            @categories=Category.all.order(:name)
        else
            redirect_to posts_path, alert: 'Вы не можете изменить этот пост'
        end
    end

    def user
        @user = Model1.find( params[:model1_id] )
        @posts = Post.where( model1: @user ).order( created_at: :desc )
    end

    def update
        @post = Post.find(params[:id])
        if model1_signed_in? && current_model1 == @post.model1
            @categories = Category.all
            if current_model1.admin? || current_model1.moderator?
                if(@post.update(post_params))
                    redirect_to @post
                else
                    @categories = Category.all
                    render 'edit', categories: @categories
                end
            else
                @post.moderated=0
                @check=1
                if(@post.update(post_params))
                    @message="Промодерировать новый пост: #{@post.title}"
                    @user=@post.model1.email
                    redirect_to controller: 'bots', action: 'clientuser', message: @message, post: @post, user: @user
                else
                    @categories = Category.all
                    render 'edit', categories: @categories
                end
            end
        else
            redirect_to posts_path, alert: 'Вы не можете изменить этот пост'
        end
    end

    def destroy
        @post=Post.find(params[:id])
        if model1_signed_in? && current_model1 == @post.model1
            @post.destroy
            redirect_to posts_path
        elsif current_model1.admin? || current_model1.moderator?
            @user1=@post.model1
            @chat_id=@user1.chatid
            @post.destroy
            if @chat_id.present?
                @check=1
                @message="Ваш пост '#{@post.title}' был удален администрацией, так как он нарушает правила нашего сайта"
                redirect_to controller: 'bots', action: 'destroy', user: @user, chat_id: @chat_id, message: @message, check: @check
            else    
                redirect_to posts_path, alert: 'Пост был успешно удален'
            end
        else
            redirect_to posts_path, alert: 'Вы не можете изменить этот пост'
        end
    end

    def create
        @post = current_model1.posts.build(post_params)
        if current_model1.admin? || current_model1.moderator?
            @post.moderated=1
            @post.moderated_at=Time.now
        else
            @post.moderated=0
        end
        if(@post.save)
            if current_model1.admin? || current_model1.moderator?
                @category = @post.category
                subscriber = @category.subscribers.pluck(:chat_id)
                @message2="В категории '#{@category.name}' вышел новый пост!\nНазвание: #{@post.title}\nАвтор: #{@post.model1.email}"
                @message = "Новый пост создан: #{@post.title}\nКатегория: #{@post.category.name}\n"
                @user=@post.model1.email
                redirect_to controller: 'bots', action: 'clientadmin', message: @message, post: @post, user: @user, subscriber: subscriber, message2: @message2
            else
                @message="Промодерировать новый пост: #{@post.title}"
                @user=@post.model1.email
                redirect_to controller: 'bots', action: 'clientuser', message: @message, post: @post, user: @user
            end
       else
            @categories=Category.all.order(:name)
            render 'new', categories: @categories
       end
    end

    private def post_params
        params.require(:post).permit(:title, :body, :category_id)
    end


    def authenticate_user!
        redirect_to new_model1_session_path, alert:"Зарегистрируйтесь чтобы получить доступ ко всем функциям" unless model1_signed_in?
      end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/edit.html.erb
<h2 align="center">Редактирование поста</h2>
<br><br>
<%= form_for :post, url: post_path(@post), method: :patch do |f| %>
    <% if @post.errors.any? %>
        <% @post.errors.full_messages.each do |msg| %>
            <div class="alert alert-danger"> <%= msg %></div>
        <% end %>
    <% end %>
    <p>
        Название поста<br>
        <%= f.text_field(:title, {:class => 'form-control'}) %>
    </p>
    <p>
        Категория<br>
        <%= f.select(:category_id, options_for_select(@categories.collect { |cat| [cat.name, cat.id]})) %>
    </p>
    <p>
    <p>
        Текст поста<br>
        <%= f.text_area(:body, {:class => 'form-control'}) %>
    </p>
    <p>
        <%= f.submit "Редактировать пост", class: "btn btn-primary" %>
    </p>
    
<% end %>

app/views/posts/index.html.erb
<h1 align="center">Главная страница</h1>
<br>
<% @i=1 %>
<h4 align="center"><%= form_tag(search_posts_path, method: :get) do %>
  <%= text_field_tag :query, params[:query] %>
  <%= submit_tag "Поиск" %>
<% end %>
</h4>
<br><br>
<% @post.each do |post| %>
    <h5><%= link_to "Статья №"+@i.to_s+" "+post.title.to_s, post_path(post)%> <% @i=@i+1 %> </h5>
    <% if post.model1 %>
    <h6>Автор: <%= link_to post.model1.email, user_posts_path( post.model1 ) if post.model1%></h6>
    <% end %>
    <h6>Категория: <%= link_to post.category.name, category_path(post.category)%></h6>
    <%= post.body %> 
    <br>
    <h7>Дата написания: <%= post.created_at.strftime('%d-%m-%Y')%></h7>
    <br><br><br>
<% end %>
<br>
<%= will_paginate @post %>

app/views/posts/laba1.html.erb
<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>1 задание по Web</title>
</head>
<body>
  <form>
    <h1>Тест на логику</h1>
    <p>1. 2+2=?  <input type="text" required pattern="4" ></p>
    <p>2. Какого цвета голубое небо?<input type="text" required pattern="[Гг]олубого|[Гг]олубое|[Гг]олубой"></p>
	<p>3. Зимой и летом одним цветом? <input type= "text" required pattern = "[Ее]ль|[ЕеЁё]лка"></p>
	<p>4. Ваш IQ по вашему мнению <input type="number" max="70"></p>
    <button>Проверить</button>
	<br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br>
	<button onclick="location.href='https://www.youtube.com/watch?v=dQw4w9WgXcQ'" type="button">НЕ НАЖИМАТЬ!!!</button>
  </form>





  <!-- Code injected by live-server -->
<script>
	// <![CDATA[  <-- For SVG support
	if ('WebSocket' in window) {
		(function () {
			function refreshCSS() {
				var sheets = [].slice.call(document.getElementsByTagName("link"));
				var head = document.getElementsByTagName("head")[0];
				for (var i = 0; i < sheets.length; ++i) {
					var elem = sheets[i];
					var parent = elem.parentElement || head;
					parent.removeChild(elem);
					var rel = elem.rel;
					if (elem.href && typeof rel != "string" || rel.length == 0 || rel.toLowerCase() == "stylesheet") {
						var url = elem.href.replace(/(&|\?)_cacheOverride=\d+/, '');
						elem.href = url + (url.indexOf('?') >= 0 ? '&' : '?') + '_cacheOverride=' + (new Date().valueOf());
					}
					parent.appendChild(elem);
				}
			}
			var protocol = window.location.protocol === 'http:' ? 'ws://' : 'wss://';
			var address = protocol + window.location.host + window.location.pathname + '/ws';
			var socket = new WebSocket(address);
			socket.onmessage = function (msg) {
				if (msg.data == 'reload') window.location.reload();
				else if (msg.data == 'refreshcss') refreshCSS();
			};
			if (sessionStorage && !sessionStorage.getItem('IsThisFirstTime_Log_From_LiveServer')) {
				console.log('Live reload enabled.');
				sessionStorage.setItem('IsThisFirstTime_Log_From_LiveServer', true);
			}
		})();
	}
	else {
		console.error('Upgrade your browser. This Browser is NOT supported WebSocket for Live-Reloading.');
	}
	// ]]>
</script>
</body>
</html>

app/views/posts/new.html.erb
<% if model1_signed_in? %>
<h1 align="center">Добавление нового поста</h1>
<br><br>
<%= form_for :post, url: posts_path do |f| %>
    <% if @post.errors.any? %>
        <% @post.errors.full_messages.each do |msg| %>
            <div class="alert alert-danger"> <%= msg %></div>
        <% end %>
    <% end %>
    <p>
        Название поста<br>
        <%= f.text_field(:title, {:class => 'form-control'}) %>
    </p>
    <p>
        Текст поста<br>
        <%= f.text_area(:body, {:class => 'form-control'}) %>
    </p>
    <p>
        Категория<br>
        <% if @categories.present? %>
        <%= f.select(:category_id, options_for_select(@categories.collect { |cat| [cat.name, cat.id]})) %>
        <% end %>
    </p>
    <p>
        <%= f.submit "Создать пост", class: "btn btn-primary" %>
    </p>
    
<% end %>

<% else %>
    <%= controller.redirect_to new_model1_session_path %>
<% end %>

app/views/posts/search.html.erb
<h1 align="center">Результат поиска:</h1>
<ul>
<% @i=1 %>
  <% @post.each do |post| %>
    <h5><%= link_to "Статья №"+@i.to_s+" "+post.title.to_s, post_path(post)%> <% @i=@i+1 %> </h5>
    <% if post.model1 %>
    <h6>Автор: <%= link_to post.model1.email, user_posts_path( post.model1 ) if post.model1%></h6>
    <% end %>
    <h6>Категория: <%= link_to post.category.name, category_path(post.category)%></h6>
    <%= post.body %> 
    <br><br>
  <% end %>
</ul>

app/views/posts/show.html.erb
<h2 align="center"><%= @post.title %> </h2>
<h6>Категория: <%= link_to @post.category.name, category_path(@post.category)%></h6>
<% if @post.model1 %>
<h6>Автор: <%= link_to @post.model1.email, user_posts_path( @post.model1 )%></h6>
<% end %>
<% if (current_model1.admin? || current_model1.moderator? || @post.model1==current_model1) && @post.moderated!=nil %>
<% if @post.moderated==true %>
    <h6 style="color: green">Moderated: <%= @post.moderated %></h6>
<% elsif @post.moderated==false %>
    <h6 style="color: red">Moderated: <%= @post.moderated %></h6>
<% end %>
<% end %>
<br>
<p> <%= @post.body %> </p>
<hr><br>
<%  if current_model1 == @post.model1%>
<%= link_to "Редактировать", edit_post_path(@post), :class => 'btn btn-warning' %>
<% end %>
<%  if current_model1 == @post.model1 || current_model1.admin? || current_model1.moderator?%>
<%= link_to "Удалить", post_path(@post), method: :delete, data: {confirm: "Вы уверены что хотите удалить статью?"}, :class => 'btn btn-danger' %>
<% end %>

<% if @post.moderated==true%>
<br><br><br><br>
<h4 align="center">Комментарии:</h4>
<br><br>
<% @i=0 %>
<% @post.comments.each do |comment| %>
    <strong> <%= comment.model1.email if comment.model1 %></strong>: <%= comment.body %> &nbsp;&nbsp;&nbsp; <small><%= comment.created_at.strftime('%d-%m-%Y %H:%M') %></small>
    <br>
    <% if comment.model1 %>
    <% if current_model1 == comment.model1%>
    <%= link_to 'Изменить', edit_post_comment_path(@post, comment) if model1_signed_in? %>&nbsp;

    <%= link_to 'Удалить', post_comment_path(@post, comment), method: :delete, data: { confirm: 'Вы уверены?' } if model1_signed_in? %>
    <% end %>
    <% end %>
    <br><br>
<% end %>
<% if model1_signed_in? %>
<hr><br>
<%= form_for([@post, @post.comments.build]) do |f| %>

<p>
    Текст комментария:<br>
    <%= f.text_area(:body, {:class => 'form-control'}) %>
</p>

<p>
    <%= f.submit("Добавить комментарий", {:class => 'btn btn-warning'}) %>
</p>
<% end %>
<% end %>
<% end %>

app/views/posts/user.html.erb
<% @i=1 %>
<% if @posts.present? %>
  <% @posts.each do |post| %>
    <% if post.model1==current_model1 || current_model1.admin? || current_model1.moderator? %>
      <%if @i==1 %>
      <h3 align="center">Все посты пользователя <%= post.model1.email %></h3>
      <br><br>
      <% end %>
      <h4><%= link_to "Статья №"+@i.to_s+": "+post.title.to_s, post_path(post)%> <% @i=@i+1 %> </h4>
      <h6>Текст: <%= post.body %> </h6>
      <% if post.moderated==true %>
        <h6 style="color: green">Moderated: <%= post.moderated %> </h6>
      <% elsif post.moderated==false %>
        <h6 style="color: red">Moderated: <%= post.moderated %> </h6>
      <% end %>
      <br>
  <% elsif post.moderated==true %>
    <%if @i==1 %>
    <h3 align="center">Все посты пользователя <%= post.model1.email %></h3>
    <br><br>
    <% end %>
      <h4><%= link_to "Статья №"+@i.to_s+": "+post.title.to_s, post_path(post)%> <% @i=@i+1 %> </h4>
      <h6>Текст: <%= post.body %> </h6>
    <br>
  <% end %>
<% end %>
<% else %>
    <h3 align="center"> У вас еще нет ни одного поста<h3>
<% end %>