config/routes.rb
Rails.application.routes.draw do
  devise_for :controllers
  devise_for :model1, controllers: { sessions: 'model1s/sessions' }
defaults format: :json do
  resource :bot, only: %i[create]
end
root 'posts#index', as: 'home'
get 'about' => 'pages#about', as: 'about'
get 'new' => 'posts#new', as: 'new'
get 'moderate' => 'moderation#moderate', as: 'moderate'
patch 'confirm' => 'moderation#confirm', as: 'confirm'
delete 'destroy' => 'moderation#destroy', as: 'destroy'
get 'laba1' => 'posts#laba1', as: 'laba1'
get 'category' => 'categories#index', as: 'cat'
get 'newcategory' => 'categories#new', as: 'newcat'
get 'postss' => 'posts#postss', as: 'postss'
get '/posts/search' => 'posts#search', as: 'search_posts'
get '/users/search' => 'users#search', as: 'search_users'
get 'user_posts/:model1_id' => 'posts#user', as: :user_posts
get 'allusers' => 'users#allusers', as: 'allusers'
get 'sendmassage' => 'bots#clientadmin', as: 'sendmassage'
get 'sendmassageadmin' => 'bots#clientuser', as: 'sendmassageadmin'
get 'comments' => 'bots#comments', as: 'comments'
get 'destroyy' => 'bots#destroy', as: 'destroyy'
patch 'resetchaid' => 'bots#resetchatid', as: 'resetchatid'
resources :moderation
resources :categories
resources :users
resources :posts do
    resources :comments
end
end

app/models/category.rb
class Category < ApplicationRecord
    validates :name, presence: true, uniqueness: true
    has_many :posts
    has_and_belongs_to_many :subscribers
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show]
  def index
    @categories = Category.all
  end

  def show
    @categories=Category.find(params[:id])
    @post = @categories.posts
  end

  def new
    if model1_signed_in? && (current_model1.admin? || current_model1.moderator?)
      @category = Category.new
    else
      redirect_to categories_path, alert: 'У вас нет прав для добавления категории'
    end
  end
  
  def edit
    if model1_signed_in? && (current_model1.admin? || current_model1.moderator?)
      @categories=Category.find(params[:id])
    else
      redirect_to categories_path, alert: 'У вас нет прав для изменения категории'
    end
  end

  def create
    @category = Category.new(category_params)
      if @category.save
        @message = "Новая категория создана: #{@category.name}"
        redirect_to controller: 'bots', action: 'clientadmin', message: @message, category: @category
      else
        render 'edit'
      end
  end

  def update
    @categories = Category.find(params[:id])
      if @categories.update(category_params)
        redirect_to @categories
      else
        render 'edit'
      end
  end

  def category_params
    params.require(:category).permit(:name)
  end

  def authenticate_user!
    redirect_to new_model1_session_path, alert:"Зарегистрируйтесь чтобы получить доступ ко всем функциям" unless model1_signed_in?
  end
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/categories/edit.html.erb
<h2 align="center">Редактирование категории</h2>
<br><br>
<%= form_for :category, url: category_path(@categories), method: :patch do |f| %>
    <% if @categories.errors.any? %>
        <% @categories.errors.full_messages.each do |msg| %>
            <div class="allert allert-danger"> <%= msg %></div>
        <% end %>
    <% end %>
    <p>
        Название категории<br>
        <%= f.text_field(:name, {:class => 'form-control'}) %>
    </p>
    <p>
        <%= f.submit "Редактировать категорию", class: "btn btn-primary" %>
    </p>
    
<% end %>

app/views/categories/index.html.erb
<h1 align="center">Категории</h1>
<br>
<% if model1_signed_in? && (current_model1.admin? || current_model1.moderator?)%>
    <%= link_to "Добавить категорию", newcat_path, class: "btn btn-primary" %>
    <br><br>
<% end %>
<% @i=1 %>
<% @categories.each do |cat| %>
    <h5><%= link_to "Категория №"+@i.to_s+" "+cat.name, category_path(cat)%> <% @i+=1 %> </h5>
    <br>
<% end %>
<br>

app/views/categories/new.html.erb
<h1 align="center">Добавление нового поста</h1>
<br><br>
<%= form_for :category, url: categories_path do |f| %>
    <% if @category.errors.any? %>
        <% @category.errors.full_messages.each do |msg| %>
            <div class="alert alert-danger"> <%= msg %></div>
        <% end %>
    <% end %>
    <p>
        Название категории<br>
        <%= f.text_field(:name, {:class => 'form-control'}) %>
    </p>
    <p>
        <%= f.submit "Создать категорию", class: "btn btn-primary" %>
    </p>
    
<% end %>

app/views/categories/show.html.erb
<h3>Название: <%= @categories.name %></h5>
</p>
<% if model1_signed_in? && (current_model1.admin? || current_model1.moderator?) %>
<%= link_to "Редактировать", edit_category_path(@categories), :class => 'btn btn-warning' %>
<% end %>
<% @i=1 %>
<br><br><br><br>
<h4>Все посты в данной категории:</h4>
<br>
<% @post.each do |post| %>
    <h5><%= link_to "Статья №"+@i.to_s+" "+post.title.to_s, post_path(post)%> <% @i=@i+1 %> </h5>
    <% if post.model1 %>
        <h6>Автор: <%= link_to post.model1.email, user_posts_path( post.model1 )%></h6>
    <% end %>
    <h6>Категория: <%= link_to post.category.name, category_path(post.category)%></h6>
    <%= post.body %> 
    <br><br><br>
<% end %>