config/routes.rb
Rails.application.routes.draw do
  devise_for :controllers
  devise_for :model1, controllers: { sessions: 'model1s/sessions' }
defaults format: :json do
  resource :bot, only: %i[create]
end
root 'posts#index', as: 'home'
get 'about' => 'pages#about', as: 'about'
get 'new' => 'posts#new', as: 'new'
get 'moderate' => 'moderation#moderate', as: 'moderate'
patch 'confirm' => 'moderation#confirm', as: 'confirm'
delete 'destroy' => 'moderation#destroy', as: 'destroy'
get 'laba1' => 'posts#laba1', as: 'laba1'
get 'category' => 'categories#index', as: 'cat'
get 'newcategory' => 'categories#new', as: 'newcat'
get 'postss' => 'posts#postss', as: 'postss'
get '/posts/search' => 'posts#search', as: 'search_posts'
get '/users/search' => 'users#search', as: 'search_users'
get 'user_posts/:model1_id' => 'posts#user', as: :user_posts
get 'allusers' => 'users#allusers', as: 'allusers'
get 'sendmassage' => 'bots#clientadmin', as: 'sendmassage'
get 'sendmassageadmin' => 'bots#clientuser', as: 'sendmassageadmin'
get 'comments' => 'bots#comments', as: 'comments'
get 'destroyy' => 'bots#destroy', as: 'destroyy'
patch 'resetchaid' => 'bots#resetchatid', as: 'resetchatid'
resources :moderation
resources :categories
resources :users
resources :posts do
    resources :comments
end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blog</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css' %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <div class="b-example-divider"></div>

  <div class="container">
    <header class="d-flex flex-wrap align-items-center justify-content-center justify-content-md-between py-3 mb-4 border-bottom">
      <div class="col-md-3 mb-2 mb-md-0">
        <a href="/" class="d-inline-flex link-body-emphasis text-decoration-none">
        </a>
      </div>

      <ul class="nav col-12 col-md-auto mb-2 justify-content-center mb-md-0">
        <li class="nav-link px-2"> <%= link_to "Главная страница", home_path %> </li>
        <% if model1_signed_in? %>
        <li class="nav-link px-2"> <%= link_to "Добавить пост", new_path %> </li>
        <% end %>
        <li class="nav-link px-2"> <%= link_to "О нас", about_path %> </li>
        <li class="nav-link px-2"> <%= link_to "Категории", cat_path %> </li>
        <% if model1_signed_in? %>
          <% if current_model1.admin? || current_model1.moderator? %>
          <li class="nav-link px-2"> <%= link_to "Пользователи", allusers_path%> </li>
          <li class="nav-link px-2"> <%= link_to "Модерация", moderate_path %> </li>
          <% end %>
          <li class="nav-link px-2"> <%= link_to "Мои посты", user_posts_path( current_model1.id ) %> </li>
          <li class="nav-link px-2"> <%= link_to "Profile", edit_model1_registration_path %> </li>
          <li class="nav-link px-2"> <%= link_to "Log out", destroy_model1_session_path, method: :delete %> </li>
        <% else %>
          <li class="nav-link px-2"> <%= link_to "Login", new_model1_session_path %> </li>
        <% end %>
      </ul>
      
    </header>
    <p class="notice"> <%= notice %></p>
    <p class="alert"> <%= alert %></p>
  </div>
    <%= yield %>
  </body>
</html>